# -*- coding: utf-8 -*-
"""LLM_cluster._Prioripynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gpXAkYmQh4Ug4XvkjNZATeTJoHXqDFbT
"""

!pip install vllm

!hf auth login

import json
import numpy as np
from vllm import LLM, SamplingParams

# Helper functions
def log_probs_to_normalized(log_probs):
    max_log = np.max(log_probs)
    exp_probs = np.exp(log_probs - max_log)
    normalized_probs = exp_probs / np.sum(exp_probs)
    return normalized_probs

def sum_to_one_normalize(lst):
    total_sum = sum(lst)
    if total_sum == 0:
        return [0] * len(lst)
    return [x / total_sum for x in lst]

# LLM query function
def query_llm(llm, desc1, desc2):
    # Few-shot prompt optimized for Python function descriptions
    prompt = f"""
Task: Determine if two Python function descriptions describe the same functionality.
- Focus on core aspects: input types, output results, and processing logic (e.g., rules for removing characters, sorting methods).
- Ignore minor details: word order, style, or additional explanations (e.g., "write a function" vs. "create a function").
- Respond only with 'Yes' or 'No' on the first line, followed by a brief explanation (max 20 words) on the next line.

Example 1:
Description 1: Write a Python function to remove the first and last occurrence of a given character from a string.
Description 2: Create a function that removes the first and last appearance of a specified character in a string.
Response:
Yes
Explanation: Both remove first and last character occurrences, identical logic.

Example 2:
Description 1: Write a Python function to calculate the volume of a triangular prism.
Description 2: Create a function to compute the volume of a rectangular prism.
Response:
No
Explanation: Triangular and rectangular prisms use different volume formulas.

Description 1: {desc1}
Description 2: {desc2}
Response:
"""
    sampling_params = SamplingParams(temperature=0.0, max_tokens=50)
    outputs = llm.generate([prompt], sampling_params)
    raw_output = outputs[0].outputs[0].text.strip()

    # Print raw LLM output for debugging
    print(f"LLM Raw Output for '{desc1[:20]}...' vs '{desc2[:20]}...':\n{raw_output}\n")

    # Extract Yes/No
    lines = raw_output.split('\n')
    answer = 'No'  # Default to No
    for line in lines:
        line = line.strip().lower()
        if line in ['yes', 'no']:
            answer = line
            break

    return answer == 'yes'

def topic_cluster_llm_hierarchical(data_path='/content/rsa_output_humannew_X.json', limit=50):
    # Load LLM
    llm = LLM(model="meta-llama/Meta-Llama-3-8B-Instruct", max_model_len=4096)

    with open(data_path, 'r') as file:
        data_01 = json.load(file)

    # Restrict to first 10 tasks
    if isinstance(data_01, list) and isinstance(data_01[0], list):
        data_01[0] = data_01[0][:min(limit, len(data_01[0]))]
    else:
        print("Data structure error; assuming data_01[0] is list of instances")
        return None

    for instance in data_01[0]:
        instruction_list = [instance.get('ori_prompt', 'Dummy prompt')] + \
                         [f.get('Generated_Description', 'Dummy desc') for f in instance.get('output', [])]
        N = len(instruction_list)

        # Initialize clusters
        clusters = {0: [0]}  # Main cluster with ori_prompt
        cluster_reps = {0: 0}  # Main cluster representative
        next_cluster_id = 1

        for i in range(1, N):
            placed = False
            # Check main cluster
            if query_llm(llm, instruction_list[cluster_reps[0]], instruction_list[i]):
                clusters[0].append(i)
                placed = True
            else:
                # Check non-main clusters
                for cid in list(clusters.keys())[1:]:
                    rep_idx = cluster_reps[cid]
                    if query_llm(llm, instruction_list[rep_idx], instruction_list[i]):
                        clusters[cid].append(i)
                        placed = True
                        break
            if not placed:
                clusters[next_cluster_id] = [i]
                cluster_reps[next_cluster_id] = i
                next_cluster_id += 1

        # Generate labels
        labels = [-1] * N
        for cid, idx_list in clusters.items():
            for idx in idx_list:
                labels[idx] = cid

        # Update Topic_RSA
        for func_idx, function in enumerate(instance.get('output', [])):
            coder_list = np.array(function.get('RSA_Prob', [0.0] * N))
            Topic_RSA = []
            main_label = labels[0]

            unique_labels = np.unique(labels)
            if len(unique_labels) == 1:
                # Single cluster: use original prompt probability
                Topic_RSA = [coder_list[0]]
            else:
                for label in unique_labels:
                    indices = np.where(np.array(labels) == label)[0]
                    if label == main_label:
                        Topic_RSA.append(coder_list[0])
                    else:
                        Topic_RSA.append(np.mean(coder_list[indices]))

            function['Topic_RSA'] = np.array(Topic_RSA)
            function['Norm_Topic_RSA'] = log_probs_to_normalized(Topic_RSA) if len(unique_labels) > 1 else Topic_RSA

    return data_01

# Data analysis function (reused, simplified for RSA accuracy)
def data_analysis(data_01):
    if not data_01 or not data_01[0]:
        return [0, 0, 0, 0.0]

    rsa_acc = 0
    total = len(data_01[0])
    for instance in data_01[0]:
        rsa_list = [f.get('Norm_Topic_RSA', [0])[0] for f in instance.get('output', [])]
        if rsa_list:
            max_index = np.argmax(rsa_list)
            if instance['output'][max_index].get('accuracy', 0) == 100.0:
                rsa_acc += 1
    return [0, 0, 0, rsa_acc / total if total > 0 else 0.0]

try:
    data_with_clusters = topic_cluster_llm_hierarchical('/content/rsa_output_humannew_X.json', limit=164)
    acc = data_analysis(data_with_clusters)
    print("RSA Accuracy for first 5 tasks:", acc[3])
except Exception as e:
    print(f"Error: {e}. Ensure the JSON file exists and vLLM is configured correctly.")

import json
import numpy as np
from vllm import LLM, SamplingParams
from datetime import datetime

# ===== 保持你原有的辅助函数不变 =====

# 在文件顶部或辅助函数区加入：
def normalize_sum_inverted(log_vals):
    vals = [-float(x) for x in log_vals]
    total = sum(vals)
    n = len(vals)
    if n == 0:
        return []
    if total == 0:
        return [1.0 / n] * n
    return [-(v / total) for v in vals]

def log_probs_to_normalized(log_probs):
    max_log = np.max(log_probs)
    exp_probs = np.exp(log_probs - max_log)
    normalized_probs = exp_probs / np.sum(exp_probs)
    return normalized_probs

def sum_to_one_normalize(lst):
    total_sum = sum(lst)
    if total_sum == 0:
        return [0] * len(lst)
    return [x / total_sum for x in lst]

def query_llm(llm, desc1, desc2):
    prompt = f"""
Task: Determine if two Python function descriptions describe the same functionality.
- Focus on core aspects: input types, output results, and processing logic (e.g., rules for removing characters, sorting methods).
- Ignore minor details: word order, style, or additional explanations (e.g., "write a function" vs. "create a function").
- Respond only with 'Yes' or 'No' on the first line, followed by a brief explanation (max 20 words) on the next line.

Example 1:
Description 1: Write a Python function to remove the first and last occurrence of a given character from a string.
Description 2: Create a function that removes the first and last appearance of a specified character in a string.
Response:
Yes
Explanation: Both remove first and last character occurrences, identical logic.

Example 2:
Description 1: Write a Python function to calculate the volume of a triangular prism.
Description 2: Create a function to compute the volume of a rectangular prism.
Response:
No
Explanation: Triangular and rectangular prisms use different volume formulas.

Description 1: {desc1}
Description 2: {desc2}
Response:
"""
    sampling_params = SamplingParams(temperature=0.0, max_tokens=50)
    outputs = llm.generate([prompt], sampling_params)
    raw_output = outputs[0].outputs[0].text.strip()

    print(f"LLM Raw Output for '{desc1[:20]}...' vs '{desc2[:20]}...':\n{raw_output}\n")

    lines = raw_output.split('\n')
    answer = 'No'
    for line in lines:
        line = line.strip().lower()
        if line in ['yes', 'no']:
            answer = line
            break
    return answer == 'yes'


# ===== 修改点：在函数内部把分簇与数值写回实例，并确保可序列化 =====
def topic_cluster_llm_hierarchical(data_path='/content/rsa_output_humannew_X.json', limit=164):
    # Load LLM
    llm = LLM(model="meta-llama/Meta-Llama-3-8B-Instruct", max_model_len=4096)

    with open(data_path, 'r', encoding='utf-8') as file:
        data_01 = json.load(file)

    # Restrict to first tasks
    if isinstance(data_01, list) and isinstance(data_01, list):
        data_01 = data_01[:min(limit, len(data_01))]
    else:
        print("Data structure error; assuming data_01[0] is list of instances")
        return None

    for instance in data_01:
        instruction_list = [instance.get('ori_prompt', 'Dummy prompt')] + \
                           [f.get('Generated_Description', 'Dummy desc') for f in instance.get('output', [])]
        N = len(instruction_list)

        # Initialize clusters
        clusters = {0: [0]}              # Main cluster with ori_prompt
        cluster_reps = {0: 0}            # Main cluster representative
        next_cluster_id = 1

        for i in range(1, N):
            placed = False
            # Check main cluster
            if query_llm(llm, instruction_list[cluster_reps[0]], instruction_list[i]):
                clusters[0].append(i)
                placed = True
            else:
                # Check non-main clusters
                for cid in list(clusters.keys())[1:]:
                    rep_idx = cluster_reps[cid]
                    if query_llm(llm, instruction_list[rep_idx], instruction_list[i]):
                        clusters[cid].append(i)
                        placed = True
                        break
            if not placed:
                clusters[next_cluster_id] = [i]
                cluster_reps[next_cluster_id] = i
                next_cluster_id += 1

        # Generate labels
        labels = [-1] * N
        for cid, idx_list in clusters.items():
            for idx in idx_list:
                labels[idx] = cid

        # 记录分簇信息到 instance（确保 JSON 友好）
        instance['__cluster_labels__'] = [int(x) for x in labels]
        instance['__clusters__'] = {str(cid): [int(x) for x in idx_list] for cid, idx_list in clusters.items()}
        instance['__cluster_reps__'] = {str(cid): int(rep) for cid, rep in cluster_reps.items()}
        instance['__instruction_list__'] = instruction_list  # 可选：便于回看每个索引对应的描述

        # Update Topic_RSA & Norm_Topic_RSA
        unique_labels = np.unique(labels)
        for func_idx, function in enumerate(instance.get('output', [])):
            # coder_list 长度通常与 instruction_list 一致
            coder_list = np.array(function.get('RSA_Prob', [0.0] * N), dtype=float)

            Topic_RSA = []
            main_label = labels[0]

            if len(unique_labels) == 1:
                # Single cluster: use original prompt probability
                Topic_RSA = [float(coder_list[0])]
                Norm_Topic_RSA = Topic_RSA[:]  # 只有一族时就用原值
            else:
                for label in unique_labels:
                    indices = np.where(np.array(labels) == label)[0]
                    if label == main_label:
                        Topic_RSA.append(float(coder_list[0]))
                    else:
                        Topic_RSA.append(float(np.mean(coder_list[indices])))

                # 归一化（对数-Softmax 正规化）
                Norm_Topic_RSA = normalize_sum_inverted(np.array(Topic_RSA, dtype=float))
                ### Here careful

            # 覆盖为可 JSON 序列化的 list
            function['Topic_RSA'] = [float(x) for x in Topic_RSA]
            function['Norm_Topic_RSA'] = [float(x) for x in (Norm_Topic_RSA if isinstance(Norm_Topic_RSA, list) else Norm_Topic_RSA.tolist())]

        # 也把 unique_labels 存一下
        instance['__unique_labels__'] = [int(x) for x in unique_labels.tolist()]

    return data_01


# ===== 你的统计函数不变 =====
def data_analysis(data_01):
    if not data_01 or not data_01:
        return [0, 0, 0, 0.0]

    rsa_acc = 0
    total = len(data_01)
    for instance in data_01:
        rsa_list = [f.get('Norm_Topic_RSA', [0])[0] for f in instance.get('output', [])]
        if rsa_list:
            max_index = int(np.argmax(rsa_list))
            if instance['output'][max_index].get('accuracy', 0) == 100.0:
                rsa_acc += 1
    return [0, 0, 0, rsa_acc / total if total > 0 else 0.0]


# ===== 新的 try 块：把所有生成信息一次性写入 JSON =====
output_json_path = 'rsa_topic_Human_re_X.json'

try:
    limit =164
    data_with_clusters = topic_cluster_llm_hierarchical('/content/rsa_output_humannew_X.json', limit=limit)
    acc = data_analysis(data_with_clusters)

    results = {
        "meta": {
            "timestamp": datetime.now().isoformat(timespec='seconds'),
            "source_file": "/content/rsa_output_humannew_X.json",
            "limit": limit,
            "rsa_accuracy": acc[3]
        },
        # 直接把处理后的详细实例写出来，包含每条任务的分族、labels、代表、以及每个函数的 Topic_RSA / Norm_Topic_RSA
        "instances": data_with_clusters
    }

    # 写文件（保留中文，缩进美化）
    with open(output_json_path, 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False, indent=2)

    print(f"已写入完整结果到: {output_json_path}")
    print("RSA Accuracy for all tasks:", acc[3])

except Exception as e:
    print(f"Error: {e}. Ensure the JSON file exists and vLLM is configured correctly.")

"""### Prior?"""

!pip install vllm

!huggingface-cli login

# -*- coding: utf-8 -*-
import json
import re
import numpy as np
from typing import List, Tuple
from vllm import LLM, SamplingParams

INPUT_PATH  = "/content/rsa_topic_Human_re_X.json"
OUTPUT_PATH = "/content/rsa_topic_Human_re_X_prior.json"

MODEL_NAME = "meta-llama/Meta-Llama-3-8B-Instruct"
MAX_MODEL_LEN = 4096


llm = LLM(model=MODEL_NAME,
          max_model_len=MAX_MODEL_LEN
              )


sampling_params = SamplingParams(n = 1,
                temperature=1,
                max_tokens = 1,
                prompt_logprobs = 1)

data = json.load(open(INPUT_PATH, "r"))

import re

def clean_function(code: str) -> str:
    """
    清理函数内容，去掉文档字符串和注释，仅保留函数定义和代码主体。
    """
    # 去掉多行或单行的文档字符串 ("""...""" 或 '''...''')
    code = re.sub(r'(""".*?"""|\'\'\'.*?\'\'\')', '', code, flags=re.S)
    # 去掉单行注释
    code = re.sub(r'#.*', '', code)
    # 去掉多余空行和首尾空格
    lines = [line.rstrip() for line in code.splitlines() if line.strip()]
    return "\n".join(lines)

for index, question in enumerate(data['instances']):
  for _ in question['output']:
    func = clean_function(_['Function'])
    outputs = llm.generate(func, sampling_params)
    start = 1
    reviewer_prob = [next(iter(token.values())).logprob for token in outputs[0].prompt_logprobs[start : -1]]
    _['Prior'] = sum(reviewer_prob)


with open(OUTPUT_PATH, 'w') as file:
    json.dump(data, file, indent=4)