# -*- coding: utf-8 -*-
"""HumanE_remake.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1utsx58PLx87GIAQSbSOSG0RNv0kZ7Yxn
"""

# 如果已装好 vllm，可以跳过这格
!pip -q install "vllm>=0.5.0" tqdm

import sys, platform, torch
print("Python:", sys.version)
print("Platform:", platform.platform())
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

!hf auth login

from vllm import LLM, SamplingParams

# ==== 路径与模型配置 ====
# 输入/输出文件（放在 /content）
INPUT_JSON  = "/content/humanevl_llama3_8b_nobootstrap.json"   # 你的输入
DESC_JSON   = "/content/rsa_with_Des_humannew.json"         # 中间输出（带 Generated_Description）
RSA_JSON    = "/content/rsa_output_humannew.json"           # 最终输出

# 模型路径：可用本地路径或 Hugging Face 仓库（需要 token 时传入 hf_token）
# 例如: "meta-llama/Meta-Llama-3-8B-Instruct"
model_path = "meta-llama/Meta-Llama-3-8B-Instruct"

# vLLM 初始化参数
llm_kwargs = dict(
    model=model_path,
    dtype="bfloat16",              # Colab 大多支持 bfloat16（A100/T4），不行可改 "float16"
    tensor_parallel_size=1,        # 单GPU
    gpu_memory_utilization=0.9,    # 尽量利用显存
)

# 需要 Hugging Face token 时传入
llm_kwargs["trust_remote_code"] = True

llm = LLM(**llm_kwargs)

# 采样参数
description_generation_params = SamplingParams(
    n=1,
    temperature=0.0,
    max_tokens=256,
)

rsa_sampling_params = SamplingParams(
    n=1,
    temperature=1.0,
    max_tokens=1,
    prompt_logprobs=1,   # 开启提示词对数概率（用于 RSA）
)
print("vLLM 已初始化。")

import re, json, textwrap
from copy import deepcopy
from tqdm import tqdm
import numpy as np

def clean_code(block: str) -> str:
    """去掉注释、docstring、多余空行"""
    if not isinstance(block, str):
        return ""
    # 行内注释
    block = re.sub(r'#.*$', '', block, flags=re.MULTILINE)
    # docstring（支持 """ 与 '''）
    block = re.sub(r'"""[\s\S]*?"""|\'\'\'[\s\S]*?\'\'\'', '', block)
    # 多余空行
    block = re.sub(r'\n\s*\n', '\n', block)
    block = re.sub(r'^\s*\n', '', block, flags=re.MULTILINE)
    return block

def rename_function(text: str) -> str:
    """将任意函数名改为 f（保持参数不变）"""
    if not isinstance(text, str):
        return ""
    pattern = r'def\s+([^\(]+)\('
    return re.sub(pattern, 'def f(', text)

def make_prompt_description(func: str) -> str:
    """构造描述生成的 few-shot 提示"""
    func_clean = clean_code(func)
    background = (
        "##Write a description for given python function##\n"
        "###Function start###\n"
        "def next_power_of_2(n):\n"
        "    if n and not n & (n - 1):\n"
        "        return n\n"
        "    count = 0\n"
        "    while n != 0:\n"
        "        n >>= 1\n"
        "        count += 1\n"
        "    return 1 << count;\n"
        "###Function end###\n"
        "###Description start###\n"
        "Write a python function to find the smallest power of 2 greater than or equal to n.\n"
        "###Description end###\n"
        "###Function start###\n"
    )
    return background + rename_function(func_clean) + "###Function end### \n###Description start###"

def process_string(s: str) -> str:
    """拿到模型输出的描述：截到第一个 ###（若有），再移除换行"""
    if not isinstance(s, str):
        return ""
    s = s.lstrip()
    hash_index = s.find("###")
    if hash_index != -1:
        return s[:hash_index].replace("\n", "")
    # 兜底：取到第一行
    newline_index = s.find("\n")
    if newline_index != -1:
        return s[:newline_index]
    return s

def split_index(lst):
    # 原脚本里未实用，保留占位
    first_index = None
    count = 0
    for i, item in enumerate(lst):
        if item == 'def':
            count += 1
            if count == 1:
                first_index = i
                break
    return first_index

def make_rsa_prompt(f: str, comment: str) -> str:
    """将描述放入 docstring，再拼接清洗后的函数定义（函数名统一为 f）"""
    clean_f = rename_function(clean_code(f))
    comment = comment if isinstance(comment, str) else ""
    return '""" ' + comment + '"""' + '\n' + clean_f

def extract_docstring(code: str):
    pattern = r'(""".*?"""|\'\'\'.*?\'\'\')'
    match = re.search(pattern, code, re.DOTALL)
    if match:
        docstring = match.group(1)
        if docstring.startswith('"""') and docstring.endswith('"""'):
            docstring = docstring[3:-3]
        elif docstring.startswith("'''") and docstring.endswith("'''"):
            docstring = docstring[3:-3]
        return textwrap.dedent(docstring)
    else:
        return None

def normalize_log_probabilities(log_probs):
    """log prob 列表 -> 归一化概率分布"""
    log_probs = np.array(log_probs, dtype=float)
    probs = np.exp(log_probs)
    total = probs.sum()
    if total == 0:
        return [0.0 for _ in log_probs]
    return (probs / total).tolist()

def get_start_index_rsa(outputs):
    start = 0
    for n, tok_dict in enumerate(outputs[0].prompt_logprobs):
        if not tok_dict:  # None 或 空
            continue
        decoded = next(iter(tok_dict.values())).decoded_token
        #if decoded in ('."""\n', ' """\n', '"""\n'):
        if decoded in ('def'):
            start = n  # 如果你想跳过三引号这个 token
            break          # 找到第一个就退出，避免多次覆盖
    return start



def strip_before_def(code: str) -> str:
    """去掉 def 之前的所有内容，只保留从第一个 def 开始的部分"""
    if not isinstance(code, str):
        return ""
    idx = code.find("def ")
    if idx == -1:
        return code.strip()
    return code[idx:].strip()

# 你的输入结构：顶层为 list；每个 epoch 是一个列表；每个 question 是 dict，含 'output' 列表
try:
    with open(DESC_JSON, "r") as f:
        data = json.load(f)
    print("加载完成。样本规模：", len(data))
except FileNotFoundError:
    raise FileNotFoundError(f"找不到文件：{INPUT_JSON}")
except json.JSONDecodeError as e:
    raise ValueError(f"JSON 解析失败：{e}")

# 为每个 function 生成描述并存入 'Generated_Description'

for question in tqdm(data, desc="Epoch loop"):
  for function in question.get('output', []):
      func_code = function.get('Function', '')
      prompt = make_prompt_description(func_code)
      outputs = llm.generate(prompt, description_generation_params)
      text = outputs[0].outputs[0].text
      desc = process_string(text)
      print(desc)  # 方便观察
      function['Generated_Description'] = desc

# 保存中间结果（可选）
with open(DESC_JSON, "w") as f:
    json.dump(data, f, indent=4)
print("已保存带 Generated_Description 的文件：", DESC_JSON)

def get_start_index_rsa(outputs):
    start = 0
    for n, tok_dict in enumerate(outputs[0].prompt_logprobs):
        if tok_dict is not None and len(tok_dict) > 0:
            entry = next(iter(tok_dict.values()))
            decoded = getattr(entry, "decoded_token", "")
            if (
                decoded.strip().startswith('"""') or
                decoded.strip().startswith("'''") or
                decoded.strip().startswith('."""')
            ):
                start = n +1
    return start


def strip_before_def(code: str) -> str:
    """去掉 def 之前的所有内容，只保留从第一个 def 开始的部分"""
    if not isinstance(code, str):
        return ""
    idx = code.find("def ")
    if idx == -1:
        return code.strip()
    return code[idx:].strip()

###Test case###
ori_description = data[2].get('ori_prompt', data[0].get('input_prompt', ''))
description = data[2]['output'][9]['Generated_Description']
function = data[2]['output'][0]
func_clean = strip_before_def(clean_code(function.get('Function', '')))
ori_prompt = make_rsa_prompt(func_clean, description)
outputs = llm.generate(ori_prompt, rsa_sampling_params)
print(get_start_index_rsa(outputs))

bad_cases = []  # 用来收集 start=0 的情况

for question in tqdm(data, desc="RSA epoch loop"):
    ori_description = question.get('ori_prompt', question.get('input_prompt', ''))

    for function in question.get('output', []):
        rsa_prob = []
        func_clean = strip_before_def(clean_code(function.get('Function', '')))

        # 1) 原始描述
        ori_prompt = make_rsa_prompt(func_clean, ori_description)
        outputs = llm.generate(ori_prompt, rsa_sampling_params)
        ori_start = get_start_index_rsa(outputs)

        print(f"[ORI] task_id={question.get('task_id','UNKNOWN')} ori_start={ori_start}")

        if ori_start == 0:
            bad_cases.append({
                "task_id": question.get("task_id", "UNKNOWN"),
                "type": "ORI",
                "prompt_logprobs": [
                    {k: {"decoded_token": v.decoded_token, "logprob": v.logprob}
                     for k, v in tok.items()} if tok else None
                    for tok in outputs[0].prompt_logprobs
                ]
            })

        s = sum(
            next(iter(tok.values())).logprob
            for tok in outputs[0].prompt_logprobs[ori_start+1:]
            if tok is not None and len(tok) > 0
        )
        rsa_prob.append(s)

        # 2) 每个候选描述
        for item in question.get('output', []):
            cand_desc = item.get('Generated_Description', '')
            cand_prompt = make_rsa_prompt(func_clean, cand_desc)
            outputs = llm.generate(cand_prompt, rsa_sampling_params)
            start = get_start_index_rsa(outputs)

            print(f"[CAND] task_id={question.get('task_id','UNKNOWN')} cand_start={start}")

            if start == 0:
                bad_cases.append({
                    "task_id": question.get("task_id", "UNKNOWN"),
                    "type": "CAND",
                    "prompt_logprobs": [
                        {k: {"decoded_token": v.decoded_token, "logprob": v.logprob}
                         for k, v in tok.items()} if tok else None
                        for tok in outputs[0].prompt_logprobs
                    ]
                })

            s = sum(
                next(iter(tok.values())).logprob
                for tok in outputs[0].prompt_logprobs[start+1:]
                if tok is not None and len(tok) > 0
            )
            rsa_prob.append(s)

        function['RSA_Prob'] = rsa_prob
        function['RSA_Norm_Prob'] = normalize_log_probabilities(rsa_prob)

# 保存最终结果
with open(RSA_JSON, "w") as f:
    json.dump(data, f, indent=4)

print("RSA 结果已保存：", RSA_JSON)

# 如果有 bad_cases 就保存小文件
BAD_JSON = RSA_JSON.replace(".json", "_badcases.json")
if bad_cases:
    with open(BAD_JSON, "w") as f:
        json.dump(bad_cases, f, indent=2, ensure_ascii=False)
    print(f"发现 {len(bad_cases)} 个 start=0 的案例，已写入 {BAD_JSON}")
else:
    print("没有发现 start=0 的案例。")