# -*- coding: utf-8 -*-
"""RSA_Coding_Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e-P-kqzhF35rtvpXMOoYAztiw5KGiBo7
"""

!pip install datasets

import json
from datasets import load_dataset
import re
import itertools
from tqdm import tqdm

dataset = load_dataset("openai/openai_humaneval")

with open('/content/humaneval_Qwen_output.json', 'r') as file:
    data_00 = json.load(file)

def format_test(test_code, function_name):
    import re

    pattern = re.compile(r'(assert .*?)(?=assert|$)', re.DOTALL)
    matches = pattern.findall(test_code)
    replaced_asserts = []
    for match in matches:
        modified_assert = re.sub(r'\bcandidate\b', function_name, match)
        modified_assert = modified_assert.replace('\n', '')
        replaced_asserts.append(modified_assert.strip())

    return replaced_asserts

def extract_function_name(prompt):
    match = re.search(r'def (\w+)\(', prompt)
    if match:
        return match.group(1)
    return None

import signal
import functools
import typing
import math
import re

def timeout(seconds=2, error_message="Timeout"):
    """
    Decorator to raise TimeoutError if function runs more than `seconds`.
    Only works reliably on Unix-based systems.
    """
    def decorator(func):
        def _handle_timeout(signum, frame):
            raise TimeoutError(error_message)

        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            # 设置信号处理器
            signal.signal(signal.SIGALRM, _handle_timeout)
            # 启动闹钟
            signal.alarm(seconds)
            try:
                result = func(*args, **kwargs)
            finally:
                # 关闭闹钟
                signal.alarm(0)
            return result
        return wrapper
    return decorator

def extract_function_name(prompt):
    match = re.search(r'def (\w+)\(', prompt)
    if match:
        return match.group(1)
    return None

import re

def format_test(test_cases, func_name):
    """
    将 test_cases（可以是包含 check(...) 的完整代码字符串，或已经提取好的列表）
    中的 assert 语句提取出来，并把 'candidate' 替换为 func_name。
    返回一个测试用例字符串列表。
    """
    # 如果传进来的是单个字符串，就先拆成行
    if isinstance(test_cases, str):
        lines = test_cases.splitlines()
    else:
        # 假设是可迭代的字符串列表，逐行收集
        lines = []
        for item in test_cases:
            if isinstance(item, str):
                lines.extend(item.splitlines())

    cases = []
    in_check = False
    for line in lines:
        # 找到 def check(candidate):
        if re.match(r'\s*def\s+check\s*\(\s*candidate\s*\)\s*:', line):
            in_check = True
            continue
        if in_check:
            # 如果又遇到下一个 def，则说明 check 体结束
            if re.match(r'\s*def\s+\w+\s*\(', line):
                break
            # 匹配 assert 语句
            m = re.match(r'\s*assert\s+(.+)', line)
            if m:
                expr = m.group(1)
                # 替换 candidate 为真实函数名
                expr = re.sub(r'\bcandidate\b', func_name, expr)
                cases.append('assert ' + expr)
    return cases


@timeout(seconds=3)  # 示例设置3秒超时
def run_single_test_case(func_str, test_case):
    """
    单进程执行某个测试用例，并在3秒内超时。
    """
    local_env = {
        "re": re,
        "typing": typing,
        "List": typing.List,
        "Tuple": typing.Tuple,
        "prod": math.prod,
    }
    exec(func_str, local_env)
    func_name = list(local_env.keys())[-1]

    test_code = compile(test_case, '<string>', 'exec')
    exec(test_code, local_env)
    return True, None


def test_function_with_signal(func_str, test_cases):
    passed_tests = 0
    errors = []
    global_env = {}

    # 先测试编译函数定义
    try:
        exec(func_str, global_env)
    except Exception as e:
        return 0.0, [f"Function definition error: {str(e)}"]

    func_name = list(global_env.keys())[-1]
    modified_test_cases = format_test(test_cases, func_name)
    total_tests = len(modified_test_cases)

    for case in modified_test_cases:
        try:
            success, error = run_single_test_case(func_str, case)
            if success:
                passed_tests += 1
            else:
                errors.append(error)
        except TimeoutError:
            errors.append(f"Test case error: {case}, Error: run out of time")
        except AssertionError:
            errors.append("Some Test Failed")
        except Exception as e:
            errors.append(f"Test case error: {case}, Exception: {str(e)}")

    pass_rate = round((passed_tests / total_tests) * 100, 2) if total_tests > 0 else 0.0
    if passed_tests == total_tests:
        errors.append("pass")

    return pass_rate, errors

n = 0
for index, question in enumerate(data_00[n:]):
  print(index+n)
  task_id = question['task_id']
  task_prompt = question['input_prompt']
  task_index = int(task_id.split('/')[-1])
  test_cases = dataset['test']['test'][task_index]
  for  answer in tqdm(question['output']):
    pass_rate, erroes = test_function_with_signal(answer['Function'], test_cases)
    answer['pass'] = pass_rate
    answer['error'] = erroes

output_file = 'humanevl_Qwen_7b_withpass.json'

# 将 k 列表写入 JSON 文件
with open(output_file, 'w') as file:
    json.dump(data_00, file, indent=4)

from google.colab import files

# 下载指定文件到本地
files.download('/content/output_v2_passrate.json')